// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/academy" | "/academy/skill/[name]" | "/agents" | "/calendar" | "/codex" | "/core-lab" | "/council" | "/inbox" | "/intake-reports" | "/knowledge-ingestion" | "/llm-activity" | "/local-queue" | "/login" | "/model-control" | "/ops" | "/project/[id]" | "/studio" | "/studio/catalog" | "/studio/idea/[id]" | "/studio/simulator" | "/system-monitor" | "/task-board" | "/task/[id]" | "/workflow-builder"
type AppRouteHandlerRoutes = "/api/token-usage"
type PageRoutes = never
type LayoutRoutes = "/" | "/inbox"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/academy": {}
  "/academy/skill/[name]": { "name": string; }
  "/agents": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/api/token-usage": {}
  "/calendar": {}
  "/codex": {}
  "/core-lab": {}
  "/council": {}
  "/inbox": {}
  "/intake-reports": {}
  "/knowledge-ingestion": {}
  "/llm-activity": {}
  "/local-queue": {}
  "/login": {}
  "/model-control": {}
  "/ops": {}
  "/project/[id]": { "id": string; }
  "/studio": {}
  "/studio/catalog": {}
  "/studio/idea/[id]": { "id": string; }
  "/studio/simulator": {}
  "/system-monitor": {}
  "/task-board": {}
  "/task/[id]": { "id": string; }
  "/workflow-builder": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/inbox": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
