// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/academy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy">> = Specific
  const handler = {} as typeof import("../../../src/app/academy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/academy/skill/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academy/skill/[name]">> = Specific
  const handler = {} as typeof import("../../../src/app/academy/skill/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../../src/app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/codex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/codex">> = Specific
  const handler = {} as typeof import("../../../src/app/codex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/core-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/core-lab">> = Specific
  const handler = {} as typeof import("../../../src/app/core-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/council/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/council">> = Specific
  const handler = {} as typeof import("../../../src/app/council/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inbox">> = Specific
  const handler = {} as typeof import("../../../src/app/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/intake-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intake-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/intake-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/knowledge-ingestion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge-ingestion">> = Specific
  const handler = {} as typeof import("../../../src/app/knowledge-ingestion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/llm-activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/llm-activity">> = Specific
  const handler = {} as typeof import("../../../src/app/llm-activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/local-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/local-queue">> = Specific
  const handler = {} as typeof import("../../../src/app/local-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/model-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/model-control">> = Specific
  const handler = {} as typeof import("../../../src/app/model-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops">> = Specific
  const handler = {} as typeof import("../../../src/app/ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/project/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/project/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/catalog">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/idea/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/idea/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/idea/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/studio/simulator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/simulator">> = Specific
  const handler = {} as typeof import("../../../src/app/studio/simulator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/system-monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-monitor">> = Specific
  const handler = {} as typeof import("../../../src/app/system-monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/task-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/task-board">> = Specific
  const handler = {} as typeof import("../../../src/app/task-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/task/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/task/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/task/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workflow-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workflow-builder">> = Specific
  const handler = {} as typeof import("../../../src/app/workflow-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/token-usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/token-usage">> = Specific
  const handler = {} as typeof import("../../../src/app/api/token-usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/inbox/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inbox">> = Specific
  const handler = {} as typeof import("../../../src/app/inbox/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
