/** shared-mind-context.md — compact SOUL+USER for Antigravity injection. */

const path = require('path');
const { VAULT } = require('./config');
const { writeIfChanged, readFileSafe } = require('./fs-utils');

function regenerateAntigravityContext() {
  const parts = [
    '<!-- AUTO-GENERATED by the vault watcher. Symlinked into ~/.gemini/antigravity/prompting/. Compact SOUL+USER for context injection. -->',
    '',
    readFileSafe(path.join(VAULT, 'SOUL.md')),
    '',
    '---',
    '',
    readFileSafe(path.join(VAULT, 'USER.md')),
  ];
  writeIfChanged(path.join(VAULT, 'shared-mind-context.md'), parts.join('\n'));
}

module.exports = { regenerateAntigravityContext };
