const fs = require('fs');
const path = require('path');
const { VAULT } = require('./config');
const { writeIfChanged, readFileSafe, encodeFilename } = require('./fs-utils');

// ── Self-wiring link graph (GBrain pattern, zero LLM calls) ─────────────

const LINK_SECTIONS = ['memories', 'projects', 'workflows', 'incidents', 'skills'];

/** Walk section dirs and collect { rel, slug, body } for every .md file. */
function collectDocs(sections) {
  const docs = [];
  for (const section of sections) {
    const dir = path.join(VAULT, section);
    if (!fs.existsSync(dir)) continue;
    const walk = [dir];
    while (walk.length) {
      const current = walk.pop();
      for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
        if (entry.isDirectory()) {
          if (!entry.name.startsWith('_') && !entry.name.startsWith('.')) walk.push(path.join(current, entry.name));
          continue;
        }
        if (!entry.name.endsWith('.md') || entry.name.startsWith('._')) continue;
        const full = path.join(current, entry.name);
        docs.push({
          rel: path.relative(VAULT, full),
          slug: entry.name.replace(/\.md$/, ''),
          body: readFileSafe(full),
        });
      }
    }
  }
  return docs;
}

/**
 * Build LINKS.md — a backlink/mention graph across the vault. Two edge
 * sources, both extracted at index time with zero LLM calls:
 *   - explicit [[wiki-links]] already present in file bodies
 *   - implicit mentions: another vault file's name/slug appearing in the text
 * Projection-only (GBrain inserts links into source files; here source
 * files are never mutated — no churn, no watcher feedback, no fighting
 * an author mid-edit).
 * Returns { linkedCount, backlinksByRel } — the per-doc inbound counts
 * feed the hybrid-search index as a ranking boost.
 */
function regenerateLinkGraph(docs) {
  // slug → set of referrers (rel paths)
  const inbound = new Map();
  const addEdge = (targetSlug, fromRel) => {
    if (!inbound.has(targetSlug)) inbound.set(targetSlug, new Set());
    inbound.get(targetSlug).add(fromRel);
  };
  const bySlug = new Map(docs.map((d) => [d.slug.toLowerCase(), d]));

  for (const doc of docs) {
    // Explicit [[wiki-links]]
    for (const m of doc.body.matchAll(/\[\[([^\]|#]+)/g)) {
      const target = m[1].trim().toLowerCase();
      if (target && target !== doc.slug.toLowerCase()) addEdge(target, doc.rel);
    }
    // Implicit mentions of other docs' slugs/titles (≥ 6 chars to avoid noise)
    const bodyLower = doc.body.toLowerCase();
    for (const [slug, target] of bySlug) {
      if (target.rel === doc.rel || slug.length < 6) continue;
      if (bodyLower.includes(slug) || bodyLower.includes(slug.replace(/[-_]/g, ' '))) {
        addEdge(slug, doc.rel);
      }
    }
  }

  const lines = [
    '# LINKS — vault backlink graph',
    '',
    '> Auto-generated by the vault watcher (self-wiring, zero LLM calls). **Do not edit by hand.**',
    '> Inbound references per document: explicit [[wiki-links]] + implicit name mentions.',
    '',
  ];
  const linked = [...inbound.entries()]
    .filter(([slug]) => bySlug.has(slug))
    .sort((a, b) => b[1].size - a[1].size);
  const backlinksByRel = new Map();
  for (const [slug, referrers] of linked) {
    const target = bySlug.get(slug);
    lines.push(`## ${slug}`, `- target: [${target.rel}](${encodeFilename(target.rel)})`);
    for (const from of [...referrers].sort()) {
      lines.push(`- ← [${from}](${encodeFilename(from)})`);
    }
    lines.push('');
    backlinksByRel.set(target.rel, (backlinksByRel.get(target.rel) || 0) + referrers.size);
  }
  writeIfChanged(path.join(VAULT, 'LINKS.md'), lines.join('\n') + '\n');
  return { linkedCount: linked.length, backlinksByRel };
}

module.exports = { LINK_SECTIONS, collectDocs, regenerateLinkGraph };
