/** SKILLS.md — walk the vault skill tree and render the skill bus index. */

const fs = require('fs');
const path = require('path');
const { VAULT } = require('./config');
const { writeIfChanged, readFileSafe, readJsonSafe, encodeFilename, listMarkdown } = require('./fs-utils');
const { parseSkillFrontmatter } = require('./frontmatter');

/**
 * Walk the vault skills tree and merge filesystem state with _index.json
 * metadata (summary, state, tags). Returns { active, candidates } where
 * each entry is { id, relPath, category, summary, tags, state }.
 * Directories starting with "_" (e.g. _candidates staging from the
 * nightly skill harvest) are collected separately and never installed.
 */
function collectSkills() {
  const skillsRoot = path.join(VAULT, 'skills');
  const index = readJsonSafe(path.join(skillsRoot, '_index.json'));
  const byId = new Map();
  if (index && Array.isArray(index.skills)) {
    for (const s of index.skills) byId.set(s.id, s);
  }

  const active = [];
  const candidates = [];
  if (!fs.existsSync(skillsRoot)) return { active, candidates };

  const subdirs = fs
    .readdirSync(skillsRoot, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const locations = [{ sub: '', dir: skillsRoot }].concat(
    subdirs.map((sub) => ({ sub, dir: path.join(skillsRoot, sub) })),
  );

  for (const { sub, dir } of locations) {
    for (const f of listMarkdown(dir)) {
      const id = f.replace(/\.md$/, '');
      const relPath = sub ? `skills/${sub}/${f}` : `skills/${f}`;
      const indexed = byId.get(id);
      let entry;
      if (indexed) {
        entry = {
          id,
          relPath,
          category: indexed.category || sub || 'general',
          summary: indexed.summary || '',
          tags: indexed.tags || [],
          state: indexed.state || 'active',
        };
      } else {
        const parsed = parseSkillFrontmatter(readFileSafe(path.join(dir, f)));
        entry = {
          id,
          relPath,
          category: parsed.category || sub || 'general',
          summary: parsed.summary,
          tags: parsed.tags,
          // Unindexed files can still carry frontmatter state (stamped by
          // the SkillsManager on archive) — respect it so an archived skill
          // whose index row was lost never re-enters the active bus.
          state: parsed.state === 'archived' ? 'archived' : 'active',
        };
      }
      // Only `_candidates/` holds skills awaiting approval. Other underscore
      // dirs are NOT skills: `_knowledge/` is the skill wiki's per-skill
      // knowledge pages (one per active skill), and listing them here used to
      // label 100+ pages "pending approval — not installed" and push ~19 KB
      // of them into SKILLS.md and AGENTS.md on every regen.
      if (sub === '_candidates') candidates.push(entry);
      else if (sub.startsWith('_')) continue;
      else if (entry.state !== 'archived') active.push(entry);
    }
  }
  return { active, candidates };
}

function regenerateSkillsIndexFile() {
  const { active, candidates } = collectSkills();
  const lines = [
    '# SKILLS — shared-mind skill bus',
    '',
    '> Auto-generated by the vault watcher. **Do not edit by hand.**',
    '> Canonical skill library for all agents (Praxis, Claude Code, Codex, Antigravity).',
    '> Check here before nontrivial or repeated-shape work; follow the linked manifest.',
    '',
  ];

  const byCategory = new Map();
  for (const s of active) {
    if (!byCategory.has(s.category)) byCategory.set(s.category, []);
    byCategory.get(s.category).push(s);
  }
  for (const category of [...byCategory.keys()].sort()) {
    lines.push(`## ${category}`, '');
    for (const s of byCategory.get(category)) {
      const tags = s.tags.length ? ` _[${s.tags.join(', ')}]_` : '';
      const summary = s.summary ? ` — ${s.summary}` : '';
      lines.push(`- [\`${s.id}\`](${encodeFilename(s.relPath)})${summary}${tags}`);
    }
    lines.push('');
  }

  if (candidates.length > 0) {
    lines.push('## candidates (pending approval — not installed)', '');
    for (const s of candidates) {
      const summary = s.summary ? ` — ${s.summary}` : '';
      lines.push(`- [\`${s.id}\`](${encodeFilename(s.relPath)})${summary}`);
    }
    lines.push('');
  }

  writeIfChanged(path.join(VAULT, 'SKILLS.md'), lines.join('\n') + '\n');
  return { active, candidates };
}

module.exports = {
  collectSkills,
  regenerateSkillsIndexFile,
};
