/**
 * AGENTS.md carries STATE.md — the Praxis-generated living current-state
 * document — in place of the March 2026 CONTEXT.md (Praxis task e524649b,
 * PART 1), and degrades to the CONTEXT-only projection when STATE.md is
 * absent. The root-doc search index includes STATE.md so hybrid search lands
 * on the current truth.
 *
 * Requiring index.js is safe: its daemon startup is behind require.main.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

const { regenerateAgentsProjection, INDEX_ROOT_DOCS } = require('../index.js');

function vaultFixture(withState) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'vault-agents-'));
  fs.writeFileSync(path.join(dir, 'SOUL.md'), '# Soul\n\nPraxis persona.', 'utf8');
  fs.writeFileSync(path.join(dir, 'USER.md'), '# User\n\nRobert.', 'utf8');
  fs.writeFileSync(
    path.join(dir, 'CONTEXT.md'),
    '# Environment & Context\n\n> Live facts moved to STATE.md.\n\n## Known Workspaces\n\n- `/Volumes/Projects/Praxis`',
    'utf8',
  );
  fs.writeFileSync(path.join(dir, 'SKILLS.md'), '# Skills\n\n- a-skill', 'utf8');
  if (withState) {
    fs.writeFileSync(
      path.join(dir, 'STATE.md'),
      [
        '<!-- AUTO-GENERATED by Praxis (src/memory/state-doc.ts). -->',
        '',
        '# Praxis live state (STATE.md)',
        '',
        'Generated: 2026-09-02 19:40:12 EDT · 2026-09-02T23:40:12Z · trigger: test',
        '',
        '## Chat (standing CLI session)',
        '',
        '- Backend: **claude-code**',
        '',
        '## Active Nexus projects (board: 2 active, 1 parked/completed)',
        '',
        '| Project | Tasks | Unblocked | Complete |',
        '|---|---|---|---|',
        '| Praxis | 765 | 327 | 418 |',
      ].join('\n'),
      'utf8',
    );
  }
  return dir;
}

describe('AGENTS.md projection', () => {
  test('includes STATE.md ahead of the CONTEXT.md pointer when Praxis has generated it', () => {
    const dir = vaultFixture(true);
    const out = regenerateAgentsProjection(dir);
    const agents = fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8');

    expect(out.includesState).toBe(true);
    expect(agents).toBe(out.text);
    expect(agents.split('\n')[0]).toContain('SOUL + USER + STATE + CONTEXT + retrieval protocol + SKILLS');
    expect(agents).toContain('# Praxis live state (STATE.md)');
    expect(agents).toContain('| Praxis | 765 | 327 | 418 |');
    expect(agents).toContain('# Environment & Context');

    const stateAt = agents.indexOf('# Praxis live state (STATE.md)');
    const contextAt = agents.indexOf('# Environment & Context');
    const soulAt = agents.indexOf('# Soul');
    const skillsAt = agents.indexOf('# Skills');
    expect(soulAt).toBeLessThan(stateAt);
    expect(stateAt).toBeLessThan(contextAt);
    expect(contextAt).toBeLessThan(skillsAt);
    expect(agents).not.toContain('chore tracking');
  });

  test('degrades to the CONTEXT-only projection when STATE.md is absent', () => {
    const dir = vaultFixture(false);
    const out = regenerateAgentsProjection(dir);
    const agents = fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8');

    expect(out.includesState).toBe(false);
    expect(agents.split('\n')[0]).toContain('SOUL + USER + CONTEXT + retrieval protocol + SKILLS');
    expect(agents).not.toContain('Praxis live state');
    expect(agents).toContain('# Environment & Context');
  });

  test('is byte-stable when nothing changed', () => {
    const dir = vaultFixture(true);
    regenerateAgentsProjection(dir);
    const first = fs.statSync(path.join(dir, 'AGENTS.md')).mtimeMs;
    regenerateAgentsProjection(dir);
    expect(fs.statSync(path.join(dir, 'AGENTS.md')).mtimeMs).toBe(first);
  });

  test('STATE.md is a root doc in the hybrid-search index, listed before CONTEXT.md', () => {
    expect(INDEX_ROOT_DOCS).toContain('STATE.md');
    expect(INDEX_ROOT_DOCS.indexOf('STATE.md')).toBeLessThan(INDEX_ROOT_DOCS.indexOf('CONTEXT.md'));
  });
});
