-- ============================================================================
-- TheNexus Database Schema for Supabase
-- Run this in Supabase SQL Editor: Dashboard -> SQL Editor -> New Query
-- ============================================================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Note: If you need vector search later, enable pgvector separately

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Projects table (replaces scanning project.json)
CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL UNIQUE,
    path TEXT NOT NULL,
    type TEXT CHECK (type IN ('web-app', 'game', 'tool')),
    description TEXT,
    vibe TEXT,
    stack JSONB DEFAULT '{}',
    urls JSONB DEFAULT '{}',
    tasks_list TEXT[], -- Simple task list (existing "tasks" array)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks table (replaces plannedFeatures array in project.json)
CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'idea' CHECK (status IN (
        'idea', 'researching', 'researched', 'planning', 'planned',
        'implementing', 'testing', 'complete', 'rejected', 'cancelled'
    )),
    priority INTEGER DEFAULT 0,
    analysis_output TEXT,
    spec_output TEXT, -- New: Detailed specification for the task (Conductor)
    research_output TEXT,
    research_interaction_id TEXT, -- For resuming deep research
    plan_output TEXT,
    walkthrough TEXT,
    task_ledger JSONB DEFAULT '[]',
    supervisor_status TEXT,
    supervisor_details JSONB,
    reasoning_level TEXT DEFAULT 'vibe',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);

-- ============================================================================
-- WORKFLOW ENGINE TABLES
-- ============================================================================

-- Workflow definitions (the visual graphs users create in React Flow)
CREATE TABLE IF NOT EXISTS workflows (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    graph_config JSONB NOT NULL,  -- React Flow nodes/edges
    version INTEGER DEFAULT 1,
    is_template BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Workflow runs (active executions of workflows)
CREATE TABLE IF NOT EXISTS runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    workflow_id UUID REFERENCES workflows(id) ON DELETE SET NULL,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    feature_id UUID REFERENCES features(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'running' CHECK (status IN (
        'pending', 'running', 'paused', 'completed', 'failed', 'cancelled'
    )),
    current_node TEXT,
    context JSONB DEFAULT '{}',
    error_message TEXT,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_runs_workflow ON runs(workflow_id);
CREATE INDEX IF NOT EXISTS idx_runs_status ON runs(status);

-- LangGraph checkpoints (for time-travel and persistence)
-- This table structure is compatible with LangGraph's PostgresSaver
CREATE TABLE IF NOT EXISTS checkpoints (
    thread_id TEXT NOT NULL,
    checkpoint_id TEXT NOT NULL,
    parent_id TEXT,
    checkpoint JSONB NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (thread_id, checkpoint_id)
);

CREATE INDEX IF NOT EXISTS idx_checkpoints_thread ON checkpoints(thread_id);
CREATE INDEX IF NOT EXISTS idx_checkpoints_parent ON checkpoints(parent_id);


-- ============================================================================
-- CONDUCTOR TABLES
-- ============================================================================

-- Tracks (high-level plans generated by the Conductor agent)
CREATE TABLE IF NOT EXISTS tracks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    feature_id UUID REFERENCES features(id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'draft' CHECK (status IN (
        'draft', 'ready', 'in_progress', 'completed', 'cancelled'
    )),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tracks_feature ON tracks(feature_id);
CREATE INDEX IF NOT EXISTS idx_tracks_project ON tracks(project_id);

-- Track Steps (individual steps within a track)
CREATE TABLE IF NOT EXISTS track_steps (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    track_id UUID REFERENCES tracks(id) ON DELETE CASCADE NOT NULL,
    step_order INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN (
        'pending', 'in_progress', 'completed', 'skipped', 'failed'
    )),
    agent_id TEXT, -- The ID of the agent assigned to this step
    run_id UUID, -- The ID of the workflow run executing this step
    output TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(track_id, step_order)
);

CREATE INDEX IF NOT EXISTS idx_track_steps_track ON track_steps(track_id);
CREATE INDEX IF NOT EXISTS idx_track_steps_status ON track_steps(status);


-- ============================================================================
-- SCHEDULER TABLES (replaces TaskStore.js file storage)
-- ============================================================================

-- Scheduled tasks
CREATE TABLE IF NOT EXISTS scheduled_tasks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    description TEXT,
    cron_expression TEXT NOT NULL,
    agent_type TEXT NOT NULL,
    agent_configuration JSONB DEFAULT '{}',
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'disabled')),
    last_run_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_status ON scheduled_tasks(status);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_next_run ON scheduled_tasks(next_run_at);

-- Execution logs
CREATE TABLE IF NOT EXISTS execution_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES scheduled_tasks(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed', 'cancelled')),
    output TEXT,
    error TEXT,
    duration_ms INTEGER,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_execution_logs_task ON execution_logs(task_id);

-- Agent memories (episodic memory for task continuity)
CREATE TABLE IF NOT EXISTS agent_memories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    task_id UUID REFERENCES scheduled_tasks(id) ON DELETE CASCADE,
    memory_type TEXT NOT NULL CHECK (memory_type IN (
        'decision', 'observation', 'feedback', 'error', 'insight', 'summary'
    )),
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    importance REAL DEFAULT 0.5,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_memories_task ON agent_memories(task_id);
CREATE INDEX IF NOT EXISTS idx_agent_memories_type ON agent_memories(memory_type);

-- ============================================================================
-- AGENT CONFIGURATION (replaces agent-config.json)
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_configs (
    id TEXT PRIMARY KEY,  -- e.g., 'chat', 'implementation', 'supervisor'
    name TEXT NOT NULL,
    description TEXT,
    default_model TEXT NOT NULL,
    system_prompt TEXT,
    parameters JSONB DEFAULT '{}',
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- USAGE TRACKING (replaces usage_stats.json)
-- ============================================================================

CREATE TABLE IF NOT EXISTS usage_stats (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL,
    model TEXT NOT NULL,
    input_tokens BIGINT DEFAULT 0,
    output_tokens BIGINT DEFAULT 0,
    total_tokens BIGINT DEFAULT 0,
    request_count INTEGER DEFAULT 0,
    UNIQUE(date, model)
);

CREATE INDEX IF NOT EXISTS idx_usage_stats_date ON usage_stats(date);

-- ============================================================================
-- TRIGGERS FOR AUTO-UPDATING TIMESTAMPS
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing triggers if they exist, then create
DROP TRIGGER IF EXISTS tr_projects_updated_at ON projects;
CREATE TRIGGER tr_projects_updated_at
    BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_features_updated_at ON features;
CREATE TRIGGER tr_features_updated_at
    BEFORE UPDATE ON features FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_workflows_updated_at ON workflows;
CREATE TRIGGER tr_workflows_updated_at
    BEFORE UPDATE ON workflows FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_tracks_updated_at ON tracks;
CREATE TRIGGER tr_tracks_updated_at
    BEFORE UPDATE ON tracks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_track_steps_updated_at ON track_steps;
CREATE TRIGGER tr_track_steps_updated_at
    BEFORE UPDATE ON track_steps FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_scheduled_tasks_updated_at ON scheduled_tasks;
CREATE TRIGGER tr_scheduled_tasks_updated_at
    BEFORE UPDATE ON scheduled_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS tr_agent_configs_updated_at ON agent_configs;
CREATE TRIGGER tr_agent_configs_updated_at
    BEFORE UPDATE ON agent_configs FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) - Basic policies
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE features ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE track_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE execution_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_stats ENABLE ROW LEVEL SECURITY;

-- For now, allow all operations (we're using service_role key from backend)
-- In production, you'd add user_id columns and proper policies
CREATE POLICY "Allow all for service role" ON projects FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON features FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON workflows FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON runs FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON checkpoints FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON tracks FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON track_steps FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON scheduled_tasks FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON execution_logs FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON agent_memories FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON agent_configs FOR ALL USING (true);
CREATE POLICY "Allow all for service role" ON usage_stats FOR ALL USING (true);


-- ============================================================================
-- CONTEXT DOCUMENTS (replaces .conductor/context/*.md files)
-- ============================================================================

CREATE TABLE IF NOT EXISTS project_contexts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    context_type TEXT NOT NULL CHECK (context_type IN (
        'product', 'product-guidelines', 'tech-stack', 'workflow', 'other'
    )),
    content TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(project_id, context_type)
);

CREATE INDEX IF NOT EXISTS idx_project_contexts_project ON project_contexts(project_id);

-- ============================================================================
-- DONE! Your database is ready.
-- ============================================================================

