/**
 * The Groundrules blind-labelling packet, read from its fixed location.
 *
 * Source of truth: Groundrules.club/data/ledger/gold-set/packet/packet.json,
 * regenerated by `python3 -m src.ledger goldset --packet ...` (task f70448bc)
 * and checked against the roster on every plain `goldset` run. This loader
 * never writes there and never takes a path from a request: the directory is
 * fixed at module level and overridable only by environment
 * (GROUNDRULES_PACKET_DIR / GROUNDRULES_GOLD_DIR) so tests can point at a
 * synthetic copy.
 *
 * What it exposes is split by stage on purpose. `stageA` is the blind set
 * (source text, row boundaries, contexts, nothing generated). `stageB` and
 * `stageC` are only handed out by the router once the earlier stage is
 * committed (docs/gold-set-design.md, sections 11 and 12). Roster traits,
 * rationales and roles are never read into the view; the roster file is
 * consulted only to learn which source unit a row and its context quotes
 * live in, so a label exports with the `sourceUnit` the scorer expects.
 *
 * The statute corpus beside the gold set (data/ledger/sources: the manifest
 * and the USLM XML / NY JSON files the scorer loads, pinned by sha256 in
 * the packet's `sources`) is read, never written, so a user-supplied
 * `within` can be checked in the same scope the scorer resolves it in: the
 * whole source unit, not just the displayed passage (`unitText`).
 */
const fs = require('fs');
const path = require('path');
const { createHash } = require('crypto');

const DEFAULT_GOLD_DIR = '/Volumes/Projects/Groundrules.club/data/ledger/gold-set';

function resolveGoldDir() {
    return process.env.GROUNDRULES_GOLD_DIR || DEFAULT_GOLD_DIR;
}
function resolvePacketDir() {
    return process.env.GROUNDRULES_PACKET_DIR || path.join(resolveGoldDir(), 'packet');
}
const DEFAULT_SOURCES_DIR = path.join(path.dirname(DEFAULT_GOLD_DIR), 'sources');
/**
 * The scorer's corpus directory. The scorer reads data/ledger/sources from
 * its fixed place whatever gold-set directory it is pointed at, so a gold-set
 * copy without a sibling `sources/manifest.json` is checked against that
 * same fixed corpus (read only, and only files whose sha256 the packet pins).
 */
function resolveSourcesDir(goldDir = resolveGoldDir()) {
    if (process.env.GROUNDRULES_SOURCES_DIR) return process.env.GROUNDRULES_SOURCES_DIR;
    const sibling = path.join(path.dirname(goldDir), 'sources');
    return fs.existsSync(path.join(sibling, 'manifest.json')) ? sibling : DEFAULT_SOURCES_DIR;
}

const sha256 = buffer => createHash('sha256').update(buffer).digest('hex');

function rosterAnchors(goldDir) {
    // Only {rowId -> {sourceId, sourceUnit, contexts: [{quote, sourceUnit|null}],
    // within|null}} leaves this function: `sourceUnit` is the unit the scorer
    // resolves the row's quotes in (the row's own, else the provision's); a
    // null context unit means the context sits in that same unit; `within`
    // is the roster's own disambiguating span for a row whose text repeats
    // inside its unit. Rationale, traits and roles stay in the file.
    try {
        const roster = JSON.parse(fs.readFileSync(path.join(goldDir, 'roster.json'), 'utf8'));
        const anchors = new Map();
        for (const provision of roster.provisions || []) {
            for (const row of provision.rows || []) {
                anchors.set(row.id, {
                    sourceId: provision.sourceId || null,
                    sourceUnit: row.sourceUnit || provision.sourceUnit || null,
                    contexts: (row.contexts || []).map(c => ({ quote: c.quote, sourceUnit: c.sourceUnit || null })),
                    within: typeof row.within === 'string' && row.within.trim() ? row.within : null,
                });
            }
        }
        return anchors;
    } catch {
        return new Map();
    }
}

// ------------------------------------------------------------------ corpus

const XML_ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };
function decodeXml(text) {
    return text.replace(/&(#x[0-9a-fA-F]+|#\d+|[a-zA-Z]+);/g, (whole, ref) => {
        if (ref[0] === '#') return String.fromCodePoint(ref[1] === 'x' || ref[1] === 'X' ? Number.parseInt(ref.slice(2), 16) : Number.parseInt(ref.slice(1), 10));
        return ref in XML_ENTITIES ? XML_ENTITIES[ref] : whole;
    });
}

/**
 * Every element carrying an `identifier` attribute, mapped to the text of
 * the element and all its descendants in document order: the same map the
 * scorer builds with ElementTree (`''.join(node.itertext())` per node, see
 * Groundrules.club/src/ledger/corpus.py load_sources). A small tokenizer
 * suffices because the USLM section files carry no CDATA or comments; both
 * are skipped anyway.
 */
function uslmUnits(xml) {
    const units = {};
    const open = []; // identifiers of the open elements that own one
    const text = xml.replace(/\r\n?/g, '\n');
    const token = /<!--[\s\S]*?-->|<!\[CDATA\[([\s\S]*?)\]\]>|<\?[\s\S]*?\?>|<!DOCTYPE[^>]*>|<\/([^\s>]+)\s*>|<([^\s/>]+)((?:\s+[^\s=]+\s*=\s*(?:"[^"]*"|'[^']*'))*)\s*(\/?)>/g;
    let last = 0;
    const emit = chunk => { if (chunk) for (const id of open) if (id !== null) units[id] += chunk; };
    let match;
    while ((match = token.exec(text)) !== null) {
        emit(decodeXml(text.slice(last, match.index)));
        last = token.lastIndex;
        if (match[1] !== undefined) { emit(match[1]); continue; }
        if (match[2] !== undefined) { open.pop(); continue; }
        if (match[3] === undefined) continue; // comment, PI, doctype
        const attrs = match[4] || '';
        const id = /(?:^|\s)identifier\s*=\s*(?:"([^"]*)"|'([^']*)')/.exec(attrs);
        const identifier = id ? decodeXml(id[1] !== undefined ? id[1] : id[2]) : null;
        if (identifier !== null && !(identifier in units)) units[identifier] = '';
        if (!match[5]) open.push(identifier);
    }
    emit(decodeXml(text.slice(last)));
    return units;
}

/**
 * Read-only access to the corpus units the scorer resolves quotes in. Each
 * source file is read from the manifest's fixed location, its sha256 checked
 * against the manifest and against the packet's own `sources` pin, and its
 * units cached until the file changes on disk. Nothing here writes.
 */
function createCorpus({ sourcesDir = resolveSourcesDir() } = {}) {
    const cache = new Map(); // sourceId -> { mtimeMs, size, sha256, units, error }
    const reject = reason => ({ ok: false, reason });
    function manifestEntry(sourceId) {
        const manifest = JSON.parse(fs.readFileSync(path.join(sourcesDir, 'manifest.json'), 'utf8'));
        return (manifest.sources || []).find(s => s.id === sourceId) || null;
    }
    function load(sourceId) {
        let info;
        try { info = manifestEntry(sourceId); } catch { return reject('manifest_unreadable'); }
        if (!info || typeof info.file !== 'string') return reject('source_not_in_manifest');
        // Manifest paths are relative to data/ledger (the sources dir's parent).
        const file = path.resolve(path.dirname(sourcesDir), info.file);
        if (!file.startsWith(`${sourcesDir}${path.sep}`)) return reject('source_outside_corpus');
        let stat;
        try { stat = fs.statSync(file); } catch { return reject('source_missing'); }
        const hit = cache.get(sourceId);
        if (hit && hit.mtimeMs === stat.mtimeMs && hit.size === stat.size && hit.pinned === info.sha256) return hit.result;
        let result;
        try {
            const bytes = fs.readFileSync(file);
            const digest = sha256(bytes);
            if (digest !== info.sha256) result = reject('source_digest_mismatch');
            else if (info.jurisdiction === 'federal') result = { ok: true, sha256: digest, units: uslmUnits(bytes.toString('utf8')) };
            else {
                const record = JSON.parse(bytes.toString('utf8'));
                if (record.activeDate !== info.corpusVersion) result = reject('source_version_mismatch');
                else result = { ok: true, sha256: digest, units: { [info.citationPath]: String(record.text || '').replace(/\\n/g, '\n') } };
            }
        } catch {
            result = reject('source_unparseable');
        }
        cache.set(sourceId, { mtimeMs: stat.mtimeMs, size: stat.size, pinned: info.sha256, result });
        return result;
    }
    /**
     * { ok: true, text } for a unit the scorer would see, else { ok: false,
     * reason }. `pinnedSha256` is the packet's digest for the source: a corpus
     * file that is not the one the packet was built from is never trusted.
     */
    function unitText(sourceId, unit, pinnedSha256 = null) {
        if (!sourceId || !unit) return reject('unit_unknown');
        const loaded = load(sourceId);
        if (!loaded.ok) return loaded;
        if (pinnedSha256 && loaded.sha256 !== pinnedSha256) return reject('source_not_pinned_by_packet');
        if (!(unit in loaded.units)) return reject('unit_not_in_source');
        return { ok: true, text: loaded.units[unit] };
    }
    return { unitText, sourcesDir };
}

function shape(raw, bytes, file, goldDir, corpus) {
    const anchors = rosterAnchors(goldDir);
    const rowsById = new Map();
    const provisions = (raw.partA?.provisions || []).map(provision => ({
        id: provision.id,
        citation: provision.citation,
        topic: provision.topic,
        jurisdiction: provision.jurisdiction,
        sourceId: provision.sourceId,
        rows: (provision.rows || []).map(row => {
            const anchor = anchors.get(row.id) || { sourceId: provision.sourceId || null, sourceUnit: null, contexts: [], within: null };
            const known = anchor.contexts;
            // `quotable`: the roster lists this context, so the scorer can
            // anchor a quote inside it (in `sourceUnit` when the context lives
            // in another unit, otherwise in the row's own unit).
            const contexts = (row.contexts || []).map((quote, index) => {
                const listed = known[index] && known[index].quote === quote ? known[index] : null;
                return { quote, sourceUnit: listed ? listed.sourceUnit : null, quotable: Boolean(listed) };
            });
            // `anchorWithin`: the roster's own span for a row whose text repeats
            // inside its unit; a quote must be unique inside it too, and the
            // export names it so the scorer can resolve the quote at all.
            // `sourceId`/`sourceUnit` (server-side view only): where the scorer
            // resolves this row's quotes, so a user `within` is checked there.
            const view = { id: row.id, label: row.label, text: row.text, contexts, anchorWithin: anchor.within, provisionId: provision.id, citation: provision.citation, sourceId: anchor.sourceId || provision.sourceId || null, sourceUnit: anchor.sourceUnit };
            rowsById.set(row.id, view);
            return { id: row.id, label: row.label, text: row.text, contexts, anchorWithin: anchor.within };
        }),
    }));
    const stageB = { title: raw.partB?.title || 'Part B', items: raw.partB?.items || [] };
    const stageC = { title: raw.partC?.title || 'Part C', items: raw.partC?.items || [] };
    const pins = new Map((raw.sources || []).map(s => [s.id, s.sha256 || null]));
    // The unit text the scorer resolves anchors in, from the corpus file the
    // packet pins; absent or unpinned sources answer { ok: false, reason }.
    const unitText = (sourceId, unit) => {
        if (!corpus) return { ok: false, reason: 'corpus_unavailable' };
        if (!pins.has(sourceId)) return { ok: false, reason: 'source_not_in_packet' };
        return corpus.unitText(sourceId, unit, pins.get(sourceId));
    };
    return {
        path: file,
        sha256: sha256(bytes),
        byteLength: bytes.length,
        schemaVersion: raw.schemaVersion,
        status: raw.status,
        purpose: raw.purpose,
        protocol: raw.protocol || [],
        filling: raw.filling || [],
        guideline: raw.guideline || { source: null, sha256: null, text: '' },
        sources: raw.sources || [],
        alignmentMinJaccard: raw.alignmentMinJaccard,
        digests: {
            rosterSha256: raw.rosterSha256 || null,
            guidelineSha256: raw.guideline?.sha256 || null,
            controlsSha256: raw.controlsSha256 || null,
            vpuSha256: raw.vpuSha256 || null,
            thresholdsSha256: raw.thresholdsSha256 || null,
        },
        counts: {
            provisions: provisions.length,
            rows: rowsById.size,
            controls: stageB.items.length,
            pairs: stageC.items.length,
        },
        stageA: { title: raw.partA?.title || 'Part A', provisions },
        stageB,
        stageC,
        rowsById,
        controlsById: new Map(stageB.items.map(item => [item.id, item])),
        pairsById: new Map(stageC.items.map(item => [item.id, item])),
        unitText,
    };
}

/**
 * A packet source re-reads packet.json whenever its mtime or size changes,
 * so a regenerated packet shows up as a new sha256 (and therefore as a
 * visible conflict for sessions bound to the old one).
 */
function createPacketSource({ packetDir = resolvePacketDir(), goldDir = resolveGoldDir(), sourcesDir = resolveSourcesDir(goldDir) } = {}) {
    let cached = null;
    const corpus = createCorpus({ sourcesDir });
    function load() {
        const file = path.join(packetDir, 'packet.json');
        const stat = fs.statSync(file);
        if (cached && cached.mtimeMs === stat.mtimeMs && cached.size === stat.size) return cached.packet;
        const bytes = fs.readFileSync(file);
        const packet = shape(JSON.parse(bytes.toString('utf8')), bytes, file, goldDir, corpus);
        cached = { mtimeMs: stat.mtimeMs, size: stat.size, packet };
        return packet;
    }
    return { load, packetDir, goldDir, sourcesDir };
}

/** Metadata safe for any reader: digests and counts, no later-stage content. */
function packetSummary(packet) {
    return {
        sha256: packet.sha256,
        path: packet.path,
        schemaVersion: packet.schemaVersion,
        status: packet.status,
        digests: packet.digests,
        counts: packet.counts,
        sources: packet.sources,
        guidelineSource: packet.guideline.source,
    };
}

module.exports = { createPacketSource, createCorpus, uslmUnits, packetSummary, resolveGoldDir, resolvePacketDir, resolveSourcesDir, DEFAULT_GOLD_DIR, DEFAULT_SOURCES_DIR };
