/**
 * Vault watcher — regenerates MEMORY.md, AGENTS.md, shared-mind-context.md
 * on every change to /Volumes/Projects/shared-mind/. Long-lived daemon
 * under launchd (com.thenexus.vault-watcher). Uses Nexus's chokidar.
 *
 * v0 of the regeneration logic — pure concatenation of identity files
 * + filesystem-walk for the index. Frontmatter auto-fill + Cortex mirror
 * come in later waves.
 */

const chokidar = require('chokidar');
const fs = require('fs');
const path = require('path');

const VAULT = '/Volumes/Projects/shared-mind';
const GENERATED_BASENAMES = new Set([
  'MEMORY.md',
  'AGENTS.md',
  'shared-mind-context.md',
]);

const DEBOUNCE_MS = 500;
let debounceTimer = null;

function log(msg) {
  process.stdout.write(`[${new Date().toISOString()}] ${msg}\n`);
}

function readFileSafe(p) {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch (e) {
    return '';
  }
}

function encodeFilename(name) {
  // Encode spaces and other URI-unsafe chars for markdown links, but
  // leave path separators as plain slashes.
  return encodeURIComponent(name).replace(/%2F/g, '/');
}

function listMarkdown(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort();
}

function regenerateMemoryIndex() {
  const lines = [
    '# MEMORY — shared-mind vault index',
    '',
    '> Auto-generated by the vault watcher. **Do not edit by hand** — your changes will be overwritten on the next file change in the vault.',
    '>',
    `> Generated: ${new Date().toISOString()}`,
    '',
  ];

  for (const section of ['memories', 'projects', 'workflows', 'incidents']) {
    const dir = path.join(VAULT, section);
    const files = listMarkdown(dir);
    if (files.length === 0) continue;
    lines.push(`## ${section}/`, '');
    for (const f of files) {
      const name = f.replace(/\.md$/, '');
      lines.push(`- [\`${name}\`](${section}/${encodeFilename(f)})`);
    }
    lines.push('');
  }

  // Skills (root + nested subdirs)
  lines.push('## skills/', '');
  const skillsRoot = path.join(VAULT, 'skills');
  if (fs.existsSync(skillsRoot)) {
    // Root-level files (e.g. lars-protocol.md)
    const rootFiles = listMarkdown(skillsRoot);
    for (const f of rootFiles) {
      const name = f.replace(/\.md$/, '');
      lines.push(`- [\`${name}\`](skills/${encodeFilename(f)})`);
    }
    // Subdirs
    const subdirs = fs
      .readdirSync(skillsRoot, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
    for (const sub of subdirs) {
      const files = listMarkdown(path.join(skillsRoot, sub));
      if (files.length === 0) continue;
      lines.push('', `### skills/${sub}/`, '');
      for (const f of files) {
        const name = f.replace(/\.md$/, '');
        lines.push(`- [\`${name}\`](skills/${sub}/${encodeFilename(f)})`);
      }
    }
  }

  const out = lines.join('\n') + '\n';
  fs.writeFileSync(path.join(VAULT, 'MEMORY.md'), out);
}

function regenerateAgentsProjection() {
  const parts = [
    '<!-- AUTO-GENERATED by the vault watcher. Do not edit. SOUL + USER + CONTEXT + MEMORY for Codex consumption. -->',
    '',
    readFileSafe(path.join(VAULT, 'SOUL.md')),
    '',
    '---',
    '',
    readFileSafe(path.join(VAULT, 'USER.md')),
    '',
    '---',
    '',
    readFileSafe(path.join(VAULT, 'CONTEXT.md')),
    '',
    '---',
    '',
    readFileSafe(path.join(VAULT, 'MEMORY.md')),
  ];
  fs.writeFileSync(path.join(VAULT, 'AGENTS.md'), parts.join('\n'));
}

function regenerateAntigravityContext() {
  const parts = [
    '<!-- AUTO-GENERATED by the vault watcher. Symlinked into ~/.gemini/antigravity/prompting/. Compact SOUL+USER for context injection. -->',
    '',
    readFileSafe(path.join(VAULT, 'SOUL.md')),
    '',
    '---',
    '',
    readFileSafe(path.join(VAULT, 'USER.md')),
  ];
  fs.writeFileSync(path.join(VAULT, 'shared-mind-context.md'), parts.join('\n'));
}

function regenerateAll(reason = 'initial') {
  try {
    regenerateMemoryIndex();
    regenerateAgentsProjection();
    regenerateAntigravityContext();
    log(`Regenerated projections (${reason})`);
  } catch (e) {
    log(`ERROR regenerating: ${e.stack || e.message}`);
  }
}

function shouldIgnore(filepath) {
  const rel = path.relative(VAULT, filepath);
  if (rel.startsWith('.git')) return true;
  if (rel.startsWith('.obsidian')) return true;
  if (rel.startsWith('_archive')) return true;
  if (path.basename(rel).startsWith('._')) return true;
  // Skip changes to our own generated files (prevent feedback loop)
  const base = path.basename(rel);
  if (GENERATED_BASENAMES.has(base) && !rel.includes('/')) return true;
  return false;
}

function onChange(event, filepath) {
  if (shouldIgnore(filepath)) return;
  const rel = path.relative(VAULT, filepath);
  log(`${event}: ${rel}`);
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => regenerateAll(`debounced ${event}`), DEBOUNCE_MS);
}

log(`Watching ${VAULT}`);
log(`Node ${process.version} pid ${process.pid}`);

const watcher = chokidar.watch(VAULT, {
  ignored: [
    /(^|[\/\\])\.git/,
    /(^|[\/\\])\.obsidian/,
    /(^|[\/\\])\._/,
    /(^|[\/\\])_archive/,
  ],
  persistent: true,
  ignoreInitial: true,
  awaitWriteFinish: { stabilityThreshold: 200, pollInterval: 50 },
});

watcher.on('add', (p) => onChange('add', p));
watcher.on('change', (p) => onChange('change', p));
watcher.on('unlink', (p) => onChange('unlink', p));
watcher.on('error', (e) => log(`watcher error: ${e.message}`));
watcher.on('ready', () => log('Watcher ready'));

// Initial regen on startup so files reflect current vault state.
regenerateAll('startup');

function shutdown(signal) {
  log(`${signal} received, shutting down`);
  watcher.close().then(() => process.exit(0));
}
process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));
