/**
 * The vault write protocol (P1-17, workflows/Vault Single Writer Design.md §4).
 *
 * ONE helper, used by every non-interactive vault writer in the fleet:
 *   - TheNexus vault-watcher  → generated mode  (owner: vault-watcher)
 *   - praxis-mind MCP         → authored mode   (lib/vault-write.js re-exports this file)
 *   - Praxis                  → the TS twin, Praxis/src/vault-write.ts
 *
 * Three guarantees:
 *   1. ATOMIC — content lands in `<dir>/.<base>.<pid>.<ts>.tmp`, then rename(2)
 *      over the target. A reader (or `git add -A`) sees the old file or the new
 *      one, never a torn one. The temp name is gitignored and watcher-ignored.
 *   2. LOCKED — the write happens under the advisory lock for the file's CLASS
 *      (see vault-lock.js), so two writers cannot interleave a read-modify-write.
 *   3. OWNED — authored mode REFUSES a file that carries the generated header,
 *      and refuses generated paths outright. Generated mode refuses to stamp a
 *      file it does not own. This is the ownership matrix, enforced in code.
 */

const fs = require('fs');
const path = require('path');
const { vaultRoot } = require('./vault-paths');
const { withLock, withLocks, withLocksAsync, acquireLock, LOCK_CLASSES } = require('./vault-lock');

/** First line of every generated projection. `<owner>` is the only writer allowed to produce it. */
const GENERATED_HEADER_PREFIX = '<!-- GENERATED: ';
const GENERATED_HEADER_SUFFIX = '; do not edit — see workflows/Vault Single Writer Design.md -->';
const GENERATED_HEADER_RE = /^<!--\s*GENERATED:\s*([a-z0-9-]+)\s*;/i;
/** Enough bytes to cover the header line on any target. */
const HEADER_PROBE_BYTES = 200;

const OWNER_WATCHER = 'vault-watcher';
const OWNER_STATE_DOC = 'praxis-state-doc';

function generatedHeader(owner) {
  return `${GENERATED_HEADER_PREFIX}${owner}${GENERATED_HEADER_SUFFIX}`;
}

/** The owner named by an existing file's header, or null when it carries none. */
function generatedOwnerOf(text) {
  const m = GENERATED_HEADER_RE.exec((text || '').slice(0, HEADER_PROBE_BYTES));
  return m ? m[1].toLowerCase() : null;
}

function readHeadSafe(abs) {
  let fd;
  try {
    fd = fs.openSync(abs, 'r');
    const buf = Buffer.alloc(HEADER_PROBE_BYTES);
    const n = fs.readSync(fd, buf, 0, HEADER_PROBE_BYTES, 0);
    return buf.slice(0, n).toString('utf8');
  } catch {
    return '';
  } finally {
    if (fd !== undefined) try { fs.closeSync(fd); } catch { /* ignore */ }
  }
}

/** Prepend the header unless the content already carries one for this owner. */
function stampGenerated(content, owner) {
  const existing = generatedOwnerOf(content);
  if (existing === owner) return content;
  return `${generatedHeader(owner)}\n${content}`;
}

// ── Ownership matrix (design §3) ─────────────────────────────────────────────

/** Watcher-generated root projections. */
const WATCHER_PROJECTIONS = new Set([
  'MEMORY.md',
  'AGENTS.md',
  'SKILLS.md',
  'LINKS.md',
  'shared-mind-context.md',
]);
/** Praxis state-doc's own projection. */
const STATE_DOC_FILE = 'STATE.md';
/** Robert-authored / hand-maintained root docs — no daemon writes these. */
const STATIC_ROOT = new Set(['SOUL.md', 'USER.md', 'CLAUDE.md', 'CONTEXT.md', 'README.md']);
/** Authored content trees. */
const AUTHORED_TOPS = new Set(['memories', 'projects', 'workflows', 'incidents', 'personas']);

/**
 * { klass, owner } for a vault-relative path.
 *   klass  — the lock class to take ('authored' | 'skills' | 'projections')
 *   owner  — 'vault-watcher' | 'praxis-state-doc' | 'praxis' | 'robert' | 'none'
 */
function classifyVaultPath(rel) {
  const norm = String(rel).replace(/\\/g, '/').replace(/^\/+/, '');
  const top = norm.split('/')[0];
  const isRoot = !norm.includes('/');
  if (isRoot && WATCHER_PROJECTIONS.has(norm)) return { klass: 'projections', owner: OWNER_WATCHER };
  if (isRoot && norm === STATE_DOC_FILE) return { klass: 'projections', owner: OWNER_STATE_DOC };
  if (isRoot && STATIC_ROOT.has(norm)) return { klass: 'authored', owner: 'robert' };
  if (top === '.index') return { klass: 'projections', owner: OWNER_WATCHER };
  if (top === '_archive') return { klass: 'authored', owner: 'none' };
  if (top === 'skills') return { klass: 'skills', owner: 'praxis' };
  if (AUTHORED_TOPS.has(top)) return { klass: 'authored', owner: 'praxis' };
  return { klass: 'authored', owner: 'praxis' };
}

function relFromVault(abs, vault) {
  return path.relative(vault, abs).replace(/\\/g, '/');
}

/** The ownership matrix, as a guard. Throws unless `rel` is authored content. */
function assertAuthored(rel, owner, verb) {
  if (owner === OWNER_WATCHER || owner === OWNER_STATE_DOC) {
    throw refusal(
      `refusing to ${verb} ${rel}: generated by ${owner}, not authored content (Vault Single Writer Design §3)`,
      'EGENERATED',
    );
  }
  if (owner === 'robert') throw refusal(`refusing to ${verb} ${rel}: Robert-authored root document`, 'EROBERT');
  if (owner === 'none') throw refusal(`refusing to ${verb} ${rel}: _archive is preservation`, 'EARCHIVE');
}

function refusal(message, code) {
  const err = new Error(message);
  err.code = code;
  return err;
}

// ── The write itself ─────────────────────────────────────────────────────────

function tempPathFor(target) {
  return path.join(
    path.dirname(target),
    `.${path.basename(target)}.${process.pid}.${Date.now()}.tmp`,
  );
}

/**
 * Atomic replace. `flag: 'wx'` keeps create-only semantics (skill-gardener):
 * the rename becomes link(2)+unlink, which fails with EEXIST if the target
 * appeared meanwhile.
 */
function atomicWrite(target, content, { flag } = {}) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  const tmp = tempPathFor(target);
  try {
    const fd = fs.openSync(tmp, 'w');
    try {
      fs.writeFileSync(fd, content, 'utf8');
      fs.fsyncSync(fd);
    } finally {
      fs.closeSync(fd);
    }
    if (flag === 'wx') {
      fs.linkSync(tmp, target); // throws EEXIST if the target exists
      fs.unlinkSync(tmp);
    } else {
      fs.renameSync(tmp, target);
    }
  } catch (err) {
    try { fs.rmSync(tmp, { force: true }); } catch { /* best-effort */ }
    throw err;
  }
}

/**
 * Write AUTHORED content into the vault.
 *
 * @param {string} abs      absolute path inside the vault
 * @param {string} content  full content (mode 'replace') or the suffix (mode 'append')
 * @param {object} opts     { mode:'replace'|'append', vault, by, flag:'wx', lockClass }
 */
function writeVaultFile(abs, content, opts = {}) {
  const vault = opts.vault || vaultRoot();
  const rel = relFromVault(abs, vault);
  const mode = opts.mode || 'replace';

  const outside = rel.startsWith('..');
  const { klass, owner } = outside ? { klass: 'authored', owner: 'praxis' } : classifyVaultPath(rel);
  if (!outside) assertAuthored(rel, owner, 'write');

  const lockClass = opts.lockClass || klass;
  // A target outside the vault root is an env-overridden subdir (tests, a
  // relocated memories/ dir): atomic + header-refusal still apply, but there is
  // no `.index/locks` to take a lock in, so the lock is skipped rather than
  // invented somewhere the other writers would never look.
  const run = () => {
    // Header refusal happens INSIDE the lock: a projection could not have been
    // stamped between the check and the write.
    const head = readHeadSafe(abs);
    const headerOwner = generatedOwnerOf(head);
    if (headerOwner) {
      throw refusal(
        `refusing to write ${rel}: file carries the GENERATED header (owner: ${headerOwner})`,
        'EGENERATED',
      );
    }
    let final = content;
    if (mode === 'append') {
      const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : '';
      final = existing + content;
    }
    atomicWrite(abs, final, { flag: opts.flag });
    return { path: abs, rel, bytes: Buffer.byteLength(final), lockClass, mode };
  };
  return outside ? run() : withLock(vault, lockClass, run, { by: opts.by || 'vault-write' });
}

/**
 * Read-modify-write one authored file under the lock: `mutate(currentOrNull)`
 * returns the new content, or null to leave the file alone. This is the shape
 * every frontmatter stamper needs — the read and the write are one critical
 * section, which a plain read + writeVaultFile is not.
 */
function updateVaultFile(abs, mutate, opts = {}) {
  const vault = opts.vault || vaultRoot();
  const rel = relFromVault(abs, vault);
  const outside = rel.startsWith('..');
  const { klass, owner } = outside ? { klass: 'authored', owner: 'praxis' } : classifyVaultPath(rel);
  if (!outside) assertAuthored(rel, owner, 'update');

  const run = () => {
    const exists = fs.existsSync(abs);
    const current = exists ? fs.readFileSync(abs, 'utf8') : null;
    if (generatedOwnerOf(current || '')) {
      throw refusal(`refusing to update ${rel}: file carries the GENERATED header`, 'EGENERATED');
    }
    const next = mutate(current);
    if (next === null || next === undefined || next === current) {
      return { path: abs, rel, changed: false };
    }
    atomicWrite(abs, next);
    return { path: abs, rel, changed: true, bytes: Buffer.byteLength(next) };
  };
  return outside ? run() : withLock(vault, opts.lockClass || klass, run, { by: opts.by || 'vault-write' });
}

/**
 * Write a GENERATED projection: stamps the header, then write-if-changed.
 * The header is added BEFORE the comparison so a byte-stable projection stays
 * byte-stable (the prompt-cache guard in fs-utils.js depends on this).
 */
function writeGeneratedFile(abs, content, opts = {}) {
  const owner = opts.owner || OWNER_WATCHER;
  const vault = opts.vault || vaultRoot();
  const rel = relFromVault(abs, vault);
  const { owner: expected } = classifyVaultPath(rel);
  if (expected !== owner) {
    throw refusal(`refusing to generate ${rel}: owned by ${expected}, not ${owner}`, 'EOWNER');
  }
  const final = stampGenerated(content, owner);
  const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (existing === final) return { path: abs, rel, changed: false, bytes: Buffer.byteLength(final) };
  atomicWrite(abs, final);
  return { path: abs, rel, changed: true, bytes: Buffer.byteLength(final) };
}

module.exports = {
  GENERATED_HEADER_PREFIX,
  GENERATED_HEADER_SUFFIX,
  GENERATED_HEADER_RE,
  OWNER_WATCHER,
  OWNER_STATE_DOC,
  WATCHER_PROJECTIONS,
  STATIC_ROOT,
  AUTHORED_TOPS,
  LOCK_CLASSES,
  generatedHeader,
  generatedOwnerOf,
  stampGenerated,
  classifyVaultPath,
  assertAuthored,
  atomicWrite,
  writeVaultFile,
  updateVaultFile,
  writeGeneratedFile,
  withLock,
  withLocks,
  withLocksAsync,
  acquireLock,
};
