"""
Implementation Nodes Package - Builder and Code Generation

Contains atomic nodes for code implementation operations.
"""

from typing import Any, Dict, List
from ..core import AtomicNode, NodeExecutionContext, NodeExecutionData

# Import the existing builder graph
from builder.agent import compile_builder_graph


class BuilderNode(AtomicNode):
    """
    Atomic node wrapper for the Builder agent mesh.
    
    The Builder performs:
    1. Scout - Reads codebase structure and identifies files
    2. Builder - Creates/modifies files using tools
    3. Check - Validates syntax and runs cross-provider review
    
    Uses Claude Opus with prompt caching for cost efficiency.
    """
    
    type_id = "builder"
    display_name = "The Builder"
    description = "High-velocity implementation agent (Scout -> Build -> Syntax Check)"
    category = "implementation"
    icon = "🔨"
    version = 1.0
    levels = ["feature"]
    default_model = "claude-opus-4-5-20251101"
    
    def get_properties(self) -> List[Dict[str, Any]]:
        return [
            {
                "displayName": "Implementation Spec",
                "name": "spec",
                "type": "string",
                "default": "",
                "description": "The implementation specification from the Architect",
                "typeOptions": {"rows": 5},
            },
            {
                "displayName": "Project Root",
                "name": "project_root",
                "type": "string",
                "default": ".",
                "description": "Root directory of the project",
                "required": True,
            },
        ]
    
    async def execute(
        self,
        ctx: NodeExecutionContext,
        items: List[NodeExecutionData]
    ) -> List[List[NodeExecutionData]]:
        """Execute the Builder subgraph."""
        
        # Get parameters
        project_root = ctx.get_node_parameter("project_root", ".")
        spec = ctx.get_node_parameter("spec", "")
        
        # Get spec from input if not in config
        if not spec and items:
            spec = items[0].json.get("plan", "") or items[0].json.get("spec", "")
        
        # Get manifest from input
        manifest = []
        dod = {}
        if items:
            manifest = items[0].json.get("manifest", [])
            dod = items[0].json.get("definition_of_done", {})
        
        # Get Nexus context
        project_context = ctx.get_project_context()
        
        # Compile the builder graph
        builder_graph = compile_builder_graph(project_root=project_root)
        
        # Build initial state
        initial_state = {
            "messages": [],
            "task_title": project_context.get("task_id", "Build Task"),
            "task_description": spec[:500] if spec else "Implement changes",
            "project_context": "",  # TODO: Load from context service
            "implementation_spec": spec,
            "file_manifest": manifest,
            "definition_of_done": dod,
            "repo_skeleton": None,  # Will be generated by scout
            "project_root": project_root,
            "modified_files": [],
            "syntax_error": None,
            "thought_signature": "",
            "loop_count": 0,
            "dialogue_history": [],
            "walkthrough": "",
        }
        
        try:
            result = await builder_graph.ainvoke(initial_state, config={"recursion_limit": 100})
            
            modified = result.get("modified_files", [])
            walkthrough = result.get("walkthrough", "")
            
            return [[NodeExecutionData(
                json={
                    "modified_files": modified,
                    "walkthrough": walkthrough,
                    "builder_summary": f"Modified {len(modified)} files",
                }
            )]]
            
        except Exception as e:
            return [[NodeExecutionData(
                json={"error": str(e)},
                error=e
            )]]
from .scout import ScoutNode
from .coder import CoderNode
from .checker import CheckerNode


__all__ = [
    "BuilderNode",
    "ScoutNode",
    "CoderNode",
    "CheckerNode",
]
